language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
    - pip install scipy
    - pip install coverage
    - pip install pytest
    - pip install pytest-cov
    - pip install h5py
    - pip install python-coveralls
    - pip install matplotlib
    - pip install multiprocess

install:
    - python setup.py install

script:
    - pytest --cov=snaptools tests
    - coveralls