language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
    - pip install coverage
    - pip install h5py
    - pip install python-coveralls

install:
    - python setup.py install

script:
    - coverage run tests/test_load.py
    - coverage run tests/test_ellipse_fit.py
    - coveralls